package org.sharpler.glag.output;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import org.fusesource.jansi.AnsiConsole;
import org.jspecify.annotations.Nullable;
import org.sharpler.glag.aggregations.RuntimeEvents;
import org.sharpler.glag.aggregations.SafepointAggregate;
import org.sharpler.glag.aggregations.SafepointLog;
import org.sharpler.glag.distribution.CumulativeDistributionPoint;
import org.sharpler.glag.records.GcIteration;
import org.sharpler.glag.records.GcLogRecords;
import org.sharpler.glag.records.GcName;
import org.sharpler.glag.records.SafepointLogRecord;
import org.sharpler.glag.records.SingleVMOperation;
import org.sharpler.glag.util.TimeUtils;

public final class HtmlOutput {
    private final Path output;

    public HtmlOutput(Path output) {
        this.output = output;
    }

    public void print(RuntimeEvents runtimeEvents, int examples) throws IOException {
        var thresholdMs = runtimeEvents.thresholdMs();
        var safepoints = runtimeEvents.safepointLog();
        var aggregate = safepoints.aggregate();
        var html = new StringBuilder(128 * 1024);

        HtmlOutputUtils.appendPageStart(html, HtmlOutputUtils.FULL_PAGE_STYLES);
        HtmlOutputUtils.appendOverview(
            html,
            aggregate,
            "This report of gc and safepoint log analysis has been generated by <strong>glag</strong> tool version 1.0-SNAPSHOT."
        );
        appendGcSection(html, runtimeEvents.gcName());
        appendSafepointSection(html, safepoints, thresholdMs);
        appendOperationsSection(html, runtimeEvents, examples);
        appendTimeToSafepointSection(html, safepoints, thresholdMs);
        appendSlowGcSections(html, runtimeEvents, examples);
        HtmlOutputUtils.appendPageEnd(html);

        Files.writeString(output, html);
    }

    private void appendGcSection(StringBuilder html, @Nullable GcName gcName) throws IOException {
        html.append("<section>");
        html.append("<h2>GC</h2>");
        if (gcName != null) {
            var name = gcName.getName();
            html.append("<p><strong>").append(HtmlOutputUtils.escapeHtml(name)).append("</strong> has been detected.</p>");
            HtmlOutputUtils.appendDocDetails(html, getClass(), "GC description", OutputUtils.DOCS_PATH.resolve("gc").resolve(name + ".md"),
                "GC '%s' description is unsupported".formatted(name));
        } else {
            html.append("<p>Failed to detect GC by logs.</p>");
            AnsiConsole.err().println("Failed to detect GC by logs");
        }
        html.append("</section>");
    }

    private void appendSafepointSection(StringBuilder html, SafepointLog safepoints, int thresholdMs) throws IOException {
        html.append("<section>");
        html.append("<h2>Safepoints</h2>");
        HtmlOutputUtils.appendDocDetails(html, getClass(), "What is a safepoint", OutputUtils.DOCS_PATH.resolve("safepoint").resolve("safepoint.md"), null);
        HtmlOutputUtils.appendDistributionSection(html, "Cumulative distribution of total safepoint time", safepoints.aggregate().totalTimeDistribution(), thresholdMs, 3);
        HtmlOutputUtils.appendDistributionSection(html, "Cumulative distribution of time inside a safepoint", safepoints.aggregate().insideTimeDistribution(), thresholdMs, 3);
        HtmlOutputUtils.appendDistributionSection(html, "Cumulative distribution of cleanup time", safepoints.aggregate().cleanupTimeDistribution(), thresholdMs, 3);
        HtmlOutputUtils.appendDistributionSection(html, "Cumulative distribution of time to leave safepoint", safepoints.aggregate().leavingTimeDistribution(), thresholdMs, 3);
        html.append("</section>");
    }

    private void appendOperationsSection(StringBuilder html, RuntimeEvents runtimeEvents, int examples) throws IOException {
        var safepoints = runtimeEvents.safepointLog();
        var thresholdMs = runtimeEvents.thresholdMs();

        html.append("<section>");
        html.append("<h2>JVM operations in safepoint</h2>");

        var unknownOperations = new HashSet<String>();
        for (var e : OutputUtils.sortedOperationAggregates(safepoints.aggregatesByType())) {
            var operationName = e.getKey();
            var operationAggregate = e.getValue();

            html.append("<section class='operation'>");
            html.append("<h3>Operation <code>").append(HtmlOutputUtils.escapeHtml(operationName)).append("</code></h3>");
            html.append("<p>Period: <strong>")
                .append(HtmlOutputUtils.format("%.3f", operationAggregate.averagePausePeriodSec()))
                .append("</strong> sec/op</p>");
            if (operationAggregate.hasInsideTimeNs()) {
                html.append("<p>Throughput lost due to pauses: <strong>")
                    .append(HtmlOutputUtils.format("%.3f", operationAggregate.insideSafepointThroughputLoss()))
                    .append("</strong> % - <strong>")
                    .append(HtmlOutputUtils.format("%.3f", operationAggregate.totalPauseThroughputLoss()))
                    .append("</strong> %</p>");
            } else {
                html.append("<p>Throughput lost due to total pauses: <strong>")
                    .append(HtmlOutputUtils.format("%.3f", operationAggregate.totalPauseThroughputLoss()))
                    .append("</strong> %</p>");
            }

            var description = OutputUtils.DOCS_PATH.resolve("operation").resolve(operationName + ".md");
            if (OutputUtils.docExists(getClass(), description)) {
                HtmlOutputUtils.appendDocDetails(html, getClass(), "Description", description, null);
            } else if (unknownOperations.add(operationName)) {
                AnsiConsole.err().printf("GC operation '%s' is unknown%n", operationName);
            }

            HtmlOutputUtils.appendDistributionSection(html, "Cumulative distribution of total time", operationAggregate.totalTimeDistribution(), thresholdMs, 4);
            HtmlOutputUtils.appendOptionalAggregateDistributions(html, operationAggregate, thresholdMs, 4);

            var slowSingleVmOperations = runtimeEvents.slowSingleVmOperations().getOrDefault(operationName, List.of());
            if (!slowSingleVmOperations.isEmpty()) {
                html.append("<h4>Slow single safepoints</h4>");
                html.append("<p>threshold = ").append(runtimeEvents.thresholdMs()).append(" ms, top ").append(examples).append("</p>");

                var topSlowVmOperations = slowSingleVmOperations
                    .stream()
                    .map(SingleVMOperation::safepointLog)
                    .sorted(Comparator.comparingLong(SafepointLogRecord::totalTimeNs).reversed())
                    .limit(examples)
                    .toList();

                for (var safepointLog : topSlowVmOperations) {
                    appendSafepointEntry(html, safepointLog, false);
                }
            }
            html.append("</section>");
        }
        html.append("</section>");
    }

    private void appendTimeToSafepointSection(StringBuilder html, SafepointLog safepoints, int thresholdMs) throws IOException {
        if (!safepoints.aggregate().hasReachingTimeNs()) {
            return;
        }
        html.append("<section>");
        html.append("<h2>Time to safepoint</h2>");
        HtmlOutputUtils.appendDocDetails(html, getClass(), "Description", OutputUtils.DOCS_PATH.resolve("safepoint").resolve("time_to_safepoint.md"), null);
        HtmlOutputUtils.appendDistributionSection(
            html,
            "Cumulative distribution",
            safepoints.aggregate().reachingTimeDistribution(),
            thresholdMs,
            2
        );
        html.append("</section>");
    }

    private static void appendSlowGcSections(StringBuilder html, RuntimeEvents runtimeEvents, int examples) {
        var slowGcs = runtimeEvents.slowGcs()
            .stream()
            .sorted(Comparator.comparingDouble((GcIteration x) -> x.gcLog().finishTimeSec() - x.gcLog().startTimeSec()).reversed())
            .limit(examples)
            .toList();
        if (!slowGcs.isEmpty()) {
            html.append("<section>");
            html.append("<h2>GC iterations with long pauses</h2>");
            html.append("<p>threshold = ").append(runtimeEvents.thresholdMs()).append(" ms, top ").append(examples).append("</p>");
            for (var slowGc : slowGcs) {
                html.append("<section class='gc-block'>");
                html.append("<h3>GC iteration ")
                    .append(slowGc.gcLog().gcNum())
                    .append(" (")
                    .append(HtmlOutputUtils.escapeHtml(TimeUtils.formatDuration(Math.round((slowGc.gcLog().finishTimeSec() - slowGc.gcLog().startTimeSec()) * 1E9))))
                    .append(")</h3>");
                appendSafepointList(html, slowGc.safepointLog());
                appendGcLogs(html, "GC logs", slowGc.gcLog());
                html.append("</section>");
            }
            html.append("</section>");
        }

        var slowSimultaneousGcs = runtimeEvents.slowSimultaneousGcs();
        if (!slowSimultaneousGcs.isEmpty()) {
            html.append("<section>");
            html.append("<h2>Simultaneous GC iterations with long pauses</h2>");
            html.append("<p>threshold = ").append(runtimeEvents.thresholdMs()).append(" ms</p>");
            for (var slowSimultaneousGc : slowSimultaneousGcs) {
                html.append("<section class='gc-block'>");
                html.append("<h3>GC iterations ")
                    .append(HtmlOutputUtils.escapeHtml(slowSimultaneousGc.gcs().stream()
                        .map(gc -> "%d (%s)".formatted(
                            gc.gcNum(),
                            TimeUtils.formatDuration(Math.round((gc.finishTimeSec() - gc.startTimeSec()) * 1E9))
                        ))
                        .toList()
                        .toString()))
                    .append("</h3>");
                appendSafepointList(html, slowSimultaneousGc.safepointLog());
                for (var slowGc : slowSimultaneousGc.gcs()) {
                    appendGcLogs(html, "GC %d logs".formatted(slowGc.gcNum()), slowGc);
                }
                html.append("</section>");
            }
            html.append("</section>");
        }
    }

    private static void appendSafepointList(StringBuilder html, List<SafepointLogRecord> safepoints) {
        html.append("<h4>Slow safepoints</h4>");
        for (var safepoint : safepoints) {
            appendSafepointEntry(html, safepoint, true);
        }
    }

    private static void appendGcLogs(StringBuilder html, String title, GcLogRecords gcLog) {
        html.append("<details class='doc'><summary>").append(HtmlOutputUtils.escapeHtml(title)).append("</summary>");
        html.append("<pre class='log-block'>");
        for (var gcEvent : gcLog.records()) {
            html.append(HtmlOutputUtils.escapeHtml(gcEvent.origin())).append('\n');
        }
        html.append("</pre></details>");
    }

    private static void appendSafepointEntry(StringBuilder html, SafepointLogRecord safepoint, boolean includeOperationName) {
        html.append("<details class='doc safepoint-entry'><summary>");
        if (includeOperationName) {
            html.append("operation = ").append(HtmlOutputUtils.escapeHtml(safepoint.operationName())).append(", ");
        }
        html.append("total time = ").append(TimeUtils.formatDuration(safepoint.totalTimeNs())).append("</summary>");
        html.append("<pre class='log-block'>").append(HtmlOutputUtils.escapeHtml(safepoint.origin())).append("</pre>");
        html.append("</details>");
    }
}
