package org.sharpler.glag.output;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import org.fusesource.jansi.AnsiConsole;
import org.sharpler.glag.aggregations.Aggregates;
import org.sharpler.glag.aggregations.SafepointAggregate;

public final class HtmlAggregatesOutput {
    private final Path output;

    public HtmlAggregatesOutput(Path output) {
        this.output = output;
    }

    public void print(Aggregates aggregates, int thresholdMs) throws IOException {
        var aggregate = aggregates.aggregate();
        var html = new StringBuilder(96 * 1024);

        HtmlOutputUtils.appendPageStart(html, getClass(), HtmlOutputUtils.AGGREGATES_PAGE_STYLES_PATH);
        HtmlOutputUtils.appendOverview(
            html,
            aggregate,
            "This report of safepoint log analysis has been generated by <strong>glag</strong> tool version 1.0-SNAPSHOT."
        );
        appendSafepointSection(html, aggregate, thresholdMs);
        appendOperationsSection(html, aggregates, thresholdMs);
        HtmlOutputUtils.appendPageEnd(html);

        Files.writeString(output, html);
    }

    private void appendSafepointSection(StringBuilder html, SafepointAggregate aggregate, int thresholdMs) throws IOException {
        html.append("<section>");
        html.append("<h2>Safepoints</h2>");
        HtmlOutputUtils.appendDocDetails(html, getClass(), "What is a safepoint", OutputUtils.DOCS_PATH.resolve("safepoint").resolve("safepoint.md"), null);
        HtmlOutputUtils.appendDistributionSection(html, "Cumulative distribution of total safepoint time", aggregate.totalTimeDistribution(), thresholdMs, 3);
        HtmlOutputUtils.appendDistributionSection(html, "Cumulative distribution of time inside a safepoint", aggregate.insideTimeDistribution(), thresholdMs, 3);
        HtmlOutputUtils.appendDistributionSection(html, "Cumulative distribution of cleanup time", aggregate.cleanupTimeDistribution(), thresholdMs, 3);
        HtmlOutputUtils.appendDistributionSection(html, "Cumulative distribution of time to leave safepoint", aggregate.leavingTimeDistribution(), thresholdMs, 3);
        if (aggregate.hasReachingTimeNs()) {
            HtmlOutputUtils.appendDocDetails(html, getClass(), "Time to safepoint", OutputUtils.DOCS_PATH.resolve("safepoint").resolve("time_to_safepoint.md"), null);
            HtmlOutputUtils.appendDistributionSection(html, "Cumulative distribution of time to safepoint", aggregate.reachingTimeDistribution(), thresholdMs, 3);
        }
        html.append("</section>");
    }

    private void appendOperationsSection(StringBuilder html, Aggregates safepoints, int thresholdMs) throws IOException {
        html.append("<section>");
        html.append("<h2>JVM operations in safepoint</h2>");

        var unknownOperations = new HashSet<String>();
        for (var e : OutputUtils.sortedOperationAggregates(safepoints.aggregatesByType())) {
            var operationName = e.getKey();
            var aggregate = e.getValue();

            html.append("<section class='operation'>");
            html.append("<h3>Operation <code>").append(HtmlOutputUtils.escapeHtml(operationName)).append("</code></h3>");
            html.append("<p>Period: <strong>")
                .append(HtmlOutputUtils.format("%.3f", aggregate.averagePausePeriodSec()))
                .append("</strong> sec/op</p>");
            if (aggregate.hasInsideTimeNs()) {
                html.append("<p>Throughput lost due to pauses: <strong>")
                    .append(HtmlOutputUtils.format("%.3f", aggregate.insideSafepointThroughputLoss()))
                    .append("</strong> % - <strong>")
                    .append(HtmlOutputUtils.format("%.3f", aggregate.totalPauseThroughputLoss()))
                    .append("</strong> %</p>");
            } else {
                html.append("<p>Throughput lost due to total pauses: <strong>")
                    .append(HtmlOutputUtils.format("%.3f", aggregate.totalPauseThroughputLoss()))
                    .append("</strong> %</p>");
            }

            var description = OutputUtils.DOCS_PATH.resolve("operation").resolve(operationName + ".md");
            if (OutputUtils.docExists(getClass(), description)) {
                HtmlOutputUtils.appendDocDetails(html, getClass(), "Description", description, null);
            } else if (unknownOperations.add(operationName)) {
                AnsiConsole.err().printf("GC operation '%s' is unknown%n", operationName);
            }

            HtmlOutputUtils.appendDistributionSection(html, "Cumulative distribution of total time", aggregate.totalTimeDistribution(), thresholdMs, 4);
            HtmlOutputUtils.appendOptionalAggregateDistributions(html, aggregate, thresholdMs, 4);
            html.append("</section>");
        }
        html.append("</section>");
    }
}
