package org.sharpler.glag.output;

import com.google.errorprone.annotations.FormatMethod;
import com.google.errorprone.annotations.FormatString;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;
import org.fusesource.jansi.AnsiConsole;
import org.jspecify.annotations.Nullable;
import org.sharpler.glag.aggregations.RuntimeEvents;
import org.sharpler.glag.aggregations.SafepointLog;
import org.sharpler.glag.distribution.CumulativeDistributionBuilder;
import org.sharpler.glag.distribution.CumulativeDistributionPoint;
import org.sharpler.glag.records.GcLogRecords;
import org.sharpler.glag.records.GcName;
import org.sharpler.glag.records.SafepointLogRecord;
import org.sharpler.glag.records.SingleVMOperation;
import org.sharpler.glag.util.TimeUtils;

public final class HtmlOutput {
    private static final Path DOCS_PATH = Path.of("docs");
    private static final Parser MARKDOWN_PARSER = Parser.builder().build();
    private static final HtmlRenderer HTML_RENDERER = HtmlRenderer.builder().build();

    private final Path output;

    public HtmlOutput(Path output) {
        this.output = output;
    }

    public void print(RuntimeEvents runtimeEvents, int examples) throws IOException {
        var thresholdMs = runtimeEvents.thresholdMs();
        var safepoints = runtimeEvents.safepointLog();
        var html = new StringBuilder(128 * 1024);

        appendPageStart(html);
        appendOverview(html, safepoints);
        appendDistributionSection(
            html,
            "Cumulative distribution of time inside a safepoint",
            CumulativeDistributionBuilder.insideDistribution(safepoints),
            thresholdMs,
            1
        );
        appendDistributionSection(
            html,
            "Cumulative distribution of time to safepoint",
            CumulativeDistributionBuilder.reachingDistribution(safepoints),
            thresholdMs,
            1
        );

        appendGcSection(html, runtimeEvents.gcName());
        appendSafepointSection(html);
        appendOperationsSection(html, runtimeEvents, examples);
        appendTimeToSafepointSection(html, safepoints, thresholdMs);
        appendSlowGcSections(html, runtimeEvents, examples);
        appendPageEnd(html);

        Files.writeString(output, html);
    }

    private static void appendOverview(StringBuilder html, SafepointLog safepoints) {
        html.append("<section class='hero'>");
        html.append("<h1>glag report</h1>");
        html.append("<p>This report of gc and safepoint log analysis has been generated by <strong>glag</strong> tool version 1.0-SNAPSHOT.</p>");
        html.append("<div class='metrics'>");
        appendMetric(
            html,
            "Throughput lost inside safepoint",
            format("%.3f %%", safepoints.events().stream().mapToLong(SafepointLogRecord::insideTimeNs).sum() / safepoints.totalLogTimeSec() / 1E7)
        );
        appendMetric(
            html,
            "Throughput lost due to total pauses",
            format("%.3f %%", safepoints.events().stream().mapToLong(SafepointLogRecord::totalTimeNs).sum() / safepoints.totalLogTimeSec() / 1E7)
        );
        appendMetric(
            html,
            "Average pause period",
            format("%.3f sec/op", safepoints.totalLogTimeSec() / safepoints.events().size())
        );
        html.append("</div>");
        html.append("</section>");
    }

    private void appendGcSection(StringBuilder html, @Nullable GcName gcName) throws IOException {
        html.append("<section>");
        html.append("<h2>GC</h2>");
        if (gcName != null) {
            var name = gcName.getName();
            html.append("<p><strong>").append(escapeHtml(name)).append("</strong> has been detected.</p>");
            appendDocDetails(html, "GC description", DOCS_PATH.resolve("gc").resolve(name + ".md"), "GC '%s' description is unsupported".formatted(name));
        } else {
            html.append("<p>Failed to detect GC by logs.</p>");
            AnsiConsole.err().println("Failed to detect GC by logs");
        }
        html.append("</section>");
    }

    private void appendSafepointSection(StringBuilder html) throws IOException {
        html.append("<section>");
        html.append("<h2>Safepoints</h2>");
        appendDocDetails(html, "What is a safepoint", DOCS_PATH.resolve("safepoint").resolve("safepoint.md"), null);
        html.append("</section>");
    }

    private void appendOperationsSection(StringBuilder html, RuntimeEvents runtimeEvents, int examples) throws IOException {
        var safepoints = runtimeEvents.safepointLog();
        var thresholdMs = runtimeEvents.thresholdMs();

        html.append("<section>");
        html.append("<h2>JVM operations in safepoint</h2>");

        var unknownOperations = new HashSet<String>();
        for (var e : safepoints.distributions().entrySet()) {
            var operationName = e.getKey();
            var events = Objects.requireNonNull(safepoints.byTypes().get(operationName));

            html.append("<section class='operation'>");
            html.append("<h3>Operation <code>").append(escapeHtml(operationName)).append("</code></h3>");
            html.append("<p>Period: <strong>")
                .append(format("%.3f", safepoints.totalLogTimeSec() / events.size()))
                .append("</strong> sec/op</p>");

            var description = DOCS_PATH.resolve("operation").resolve(operationName + ".md");
            if (docExists(description)) {
                appendDocDetails(html, "Description", description, null);
            } else if (unknownOperations.add(operationName)) {
                AnsiConsole.err().printf("GC operation '%s' is unknown%n", operationName);
            }

            appendDistributionSection(html, "Cumulative distribution", e.getValue(), thresholdMs, 2);

            var slowSingleVmOperations = runtimeEvents.slowSingleVmOperations().getOrDefault(operationName, List.of());
            if (!slowSingleVmOperations.isEmpty()) {
                html.append("<h4>Slow single safepoints</h4>");
                html.append("<p>threshold = ").append(runtimeEvents.thresholdMs()).append(" ms, top ").append(examples).append("</p>");

                var topSlowVmOperations = slowSingleVmOperations
                    .stream()
                    .map(SingleVMOperation::safepointLog)
                    .sorted(Comparator.comparingLong(SafepointLogRecord::totalTimeNs).reversed())
                    .limit(examples)
                    .toList();

                for (var safepointLog : topSlowVmOperations) {
                    appendSafepointEntry(html, safepointLog, false);
                }
            }
            html.append("</section>");
        }
        html.append("</section>");
    }

    private void appendTimeToSafepointSection(StringBuilder html, SafepointLog safepoints, int thresholdMs) throws IOException {
        html.append("<section>");
        html.append("<h2>Time to safepoint</h2>");
        appendDocDetails(html, "Description", DOCS_PATH.resolve("safepoint").resolve("time_to_safepoint.md"), null);
        appendDistributionSection(
            html,
            "Cumulative distribution",
            CumulativeDistributionBuilder.reachingDistribution(safepoints),
            thresholdMs,
            2
        );
        html.append("</section>");
    }

    private static void appendSlowGcSections(StringBuilder html, RuntimeEvents runtimeEvents, int examples) {
        var slowGcs = runtimeEvents.slowGcs()
            .stream()
            .sorted(Comparator.comparingDouble(x -> x.gcLog().withRange().finish() - x.gcLog().withRange().start()))
            .limit(examples)
            .toList();
        if (!slowGcs.isEmpty()) {
            html.append("<section>");
            html.append("<h2>GC iterations with long pauses</h2>");
            html.append("<p>threshold = ").append(runtimeEvents.thresholdMs()).append(" ms, top ").append(examples).append("</p>");
            for (var slowGc : slowGcs) {
                html.append("<section class='gc-block'>");
                html.append("<h3>GC iteration ").append(slowGc.gcLog().gcNum()).append("</h3>");
                appendSafepointList(html, slowGc.safepointLog());
                appendGcLogs(html, "GC logs", slowGc.gcLog());
                html.append("</section>");
            }
            html.append("</section>");
        }

        var slowSimultaneousGcs = runtimeEvents.slowSimultaneousGcs();
        if (!slowSimultaneousGcs.isEmpty()) {
            html.append("<section>");
            html.append("<h2>Simultaneous GC iterations with long pauses</h2>");
            html.append("<p>threshold = ").append(runtimeEvents.thresholdMs()).append(" ms</p>");
            for (var slowSimultaneousGc : slowSimultaneousGcs) {
                html.append("<section class='gc-block'>");
                html.append("<h3>GC iterations ")
                    .append(escapeHtml(Arrays.toString(slowSimultaneousGc.gcs().stream().mapToInt(GcLogRecords::gcNum).toArray())))
                    .append("</h3>");
                appendSafepointList(html, slowSimultaneousGc.safepointLog());
                for (var slowGc : slowSimultaneousGc.gcs()) {
                    appendGcLogs(html, "GC %d logs".formatted(slowGc.gcNum()), slowGc);
                }
                html.append("</section>");
            }
            html.append("</section>");
        }
    }

    private static void appendSafepointList(StringBuilder html, List<SafepointLogRecord> safepoints) {
        html.append("<h4>Slow safepoints</h4>");
        for (var safepoint : safepoints) {
            appendSafepointEntry(html, safepoint, true);
        }
    }

    private static void appendGcLogs(StringBuilder html, String title, GcLogRecords gcLog) {
        html.append("<details class='doc'><summary>").append(escapeHtml(title)).append("</summary>");
        html.append("<pre class='log-block'>");
        for (var gcEvent : gcLog.records()) {
            html.append(escapeHtml(gcEvent.origin())).append('\n');
        }
        html.append("</pre></details>");
    }

    private static void appendSafepointEntry(StringBuilder html, SafepointLogRecord safepoint, boolean includeOperationName) {
        html.append("<details class='doc safepoint-entry'><summary>");
        if (includeOperationName) {
            html.append("operation = ").append(escapeHtml(safepoint.operationName())).append(", ");
        }
        html.append("total time = ").append(TimeUtils.formatDuration(safepoint.totalTimeNs())).append("</summary>");
        html.append("<pre class='log-block'>").append(escapeHtml(safepoint.origin())).append("</pre>");
        html.append("</details>");
    }

    private static void appendDistributionSection(
        StringBuilder html,
        String title,
        List<CumulativeDistributionPoint> points,
        double thresholdMs,
        int headingLevel
    ) {
        if (points.isEmpty()) {
            return;
        }
        html.append('<').append('h').append(headingLevel).append('>')
            .append(escapeHtml(title))
            .append("</h").append(headingLevel).append('>');
        html.append("<div class='distribution-grid'>");
        appendDistributionChart(html, points, thresholdMs);
        appendDistributionTable(html, points, thresholdMs);
        html.append("</div>");
    }

    private static void appendDistributionChart(StringBuilder html, List<CumulativeDistributionPoint> points, double thresholdMs) {
        var width = 760d;
        var height = 288d;
        var left = 56d;
        var right = 84d;
        var top = 28d;
        var bottom = 32d;
        var plotWidth = width - left - right;
        var plotHeight = height - top - bottom;
        var maxTimingMs = points.getLast().value() / 1E6;
        var normalizedMaxTimingMs = maxTimingMs == 0d ? 1d : maxTimingMs;

        html.append("<figure class='chart-card'>");
        html.append("<svg viewBox='0 0 760 288' role='img' aria-label='Cumulative distribution chart'>");
        html.append("<rect x='0' y='0' width='760' height='288' rx='14' class='chart-bg'/>");
        html.append("<line x1='").append(format("%.2f", left)).append("' y1='").append(format("%.2f", top)).append("' x2='")
            .append(format("%.2f", left)).append("' y2='").append(format("%.2f", top + plotHeight)).append("' class='axis'/>");
        html.append("<line x1='").append(format("%.2f", left)).append("' y1='").append(format("%.2f", top + plotHeight)).append("' x2='")
            .append(format("%.2f", left + plotWidth)).append("' y2='").append(format("%.2f", top + plotHeight)).append("' class='axis'/>");

        if (thresholdMs > 0d && thresholdMs <= normalizedMaxTimingMs) {
            var thresholdY = top + plotHeight - (thresholdMs / normalizedMaxTimingMs) * plotHeight;
            var thresholdIntersection = findThresholdIntersection(points, thresholdMs);
            html.append("<line x1='").append(format("%.2f", left)).append("' y1='").append(format("%.2f", thresholdY)).append("' x2='")
                .append(format("%.2f", left + plotWidth)).append("' y2='")
                .append(format("%.2f", thresholdY)).append("' class='threshold-line'/>");
            html.append("<text x='16' y='").append(format("%.2f", thresholdY - 6d)).append("' class='axis-label threshold-label'>")
                .append(escapeHtml(format("%.3f ms", thresholdMs)))
                .append("</text>");
            if (!Double.isNaN(thresholdIntersection)) {
                var thresholdX = left + thresholdIntersection * plotWidth;
                var thresholdProbabilityText = format("%.2f %%", thresholdIntersection * 100d);
                var thresholdLabelWidth = 44d;
                var thresholdLabelX = Math.min(thresholdX + 8d, left + plotWidth - thresholdLabelWidth);
                html.append("<circle cx='").append(format("%.2f", thresholdX)).append("' cy='")
                    .append(format("%.2f", thresholdY)).append("' r='4' class='threshold-point'/>");
                html.append("<text x='").append(format("%.2f", thresholdLabelX)).append("' y='")
                    .append(format("%.2f", thresholdY - 8d)).append("' class='axis-label threshold-label'>")
                    .append(escapeHtml(thresholdProbabilityText))
                    .append("</text>");
            }
        }

        html.append("<polyline class='distribution-line' points='");
        if (points.getFirst().prob() > 0d) {
            html.append(format("%.2f,%.2f ", left, top + plotHeight));
        }
        for (var point : points) {
            var timingMs = point.value() / 1E6;
            var x = left + point.prob() * plotWidth;
            var y = top + plotHeight - (timingMs / normalizedMaxTimingMs) * plotHeight;
            html.append(format("%.2f,%.2f ", x, y));
        }
        html.append("'/>");

        html.append("<text x='").append(format("%.2f", left)).append("' y='").append(format("%.2f", top + plotHeight + 16d)).append("' class='axis-label'>0%</text>");
        html.append("<text x='").append(format("%.2f", left + plotWidth - 26d)).append("' y='")
            .append(format("%.2f", top + plotHeight + 16d)).append("' class='axis-label'>100%</text>");
        html.append("<text x='12' y='").append(format("%.2f", top - 6d)).append("' class='axis-label'>")
            .append(escapeHtml(format("%.3f ms", normalizedMaxTimingMs))).append("</text>");
        html.append("<text x='32' y='").append(format("%.2f", top + plotHeight + 4d)).append("' class='axis-label'>0</text>");
        html.append("</svg>");
        html.append("<figcaption>Probability on the X axis, timing in ms on the Y axis.</figcaption>");
        html.append("</figure>");
    }

    private static double findThresholdIntersection(List<CumulativeDistributionPoint> points, double thresholdMs) {
        var previousProbability = 0d;
        var previousTimingMs = 0d;
        for (var point : points) {
            var currentProbability = point.prob();
            var currentTimingMs = point.value() / 1E6;
            if (thresholdMs <= currentTimingMs) {
                if (currentTimingMs == previousTimingMs) {
                    return currentProbability;
                }
                var ratio = (thresholdMs - previousTimingMs) / (currentTimingMs - previousTimingMs);
                return previousProbability + ratio * (currentProbability - previousProbability);
            }
            previousProbability = currentProbability;
            previousTimingMs = currentTimingMs;
        }
        return Double.NaN;
    }

    private static void appendDistributionTable(StringBuilder html, List<CumulativeDistributionPoint> points, double thresholdMs) {
        html.append("<details class='doc table-details'><summary>Show data points</summary>");
        appendDistributionTableContent(html, points, thresholdMs);
        html.append("</details>");
    }

    private static void appendDistributionTableContent(StringBuilder html, List<CumulativeDistributionPoint> points, double thresholdMs) {
        html.append("<table><thead><tr><th>Timing (ms)</th><th>Probability (%)</th></tr></thead><tbody>");
        for (var point : points) {
            var timingMs = point.value() / 1E6;
            html.append("<tr");
            if (timingMs > thresholdMs) {
                html.append(" class='over-threshold'");
            }
            html.append("><td>")
                .append(escapeHtml(format("%.3f", timingMs)))
                .append("</td><td>")
                .append(escapeHtml(format("%.2f", point.prob() * 100d)))
                .append("</td></tr>");
        }
        html.append("</tbody></table>");
    }

    private void appendDocDetails(StringBuilder html, String summary, Path docPath, @Nullable String missingMessage) throws IOException {
        if (!docExists(docPath)) {
            if (missingMessage != null) {
                AnsiConsole.err().println(missingMessage);
            }
            return;
        }

        html.append("<details class='doc'><summary>").append(escapeHtml(summary)).append("</summary>");
        html.append("<div class='doc-body'>").append(renderMarkdown(readDoc(docPath))).append("</div>");
        html.append("</details>");
    }

    private static void appendMetric(StringBuilder html, String name, String value) {
        html.append("<div class='metric'><span class='metric-name'>")
            .append(escapeHtml(name))
            .append("</span><strong>")
            .append(escapeHtml(value))
            .append("</strong></div>");
    }

    private static void appendPageStart(StringBuilder html) {
        html.append("""
            <!DOCTYPE html>
            <html lang='en'>
            <head>
            <meta charset='UTF-8'>
            <meta name='viewport' content='width=device-width, initial-scale=1'>
            <title>glag report</title>
            <style>
            :root {
              --bg: #f4f1ea;
              --paper: #fffaf2;
              --paper-2: #fdf6eb;
              --ink: #1f241f;
              --muted: #5f675d;
              --line: #d8cdbb;
              --accent: #174c3c;
              --accent-soft: #dceee6;
              --warn: #a83c32;
              --warn-soft: #fbe2de;
              --shadow: 0 10px 35px rgba(35, 34, 29, 0.08);
            }
            * { box-sizing: border-box; }
            body {
              margin: 0;
              background:
                radial-gradient(circle at top left, rgba(23, 76, 60, 0.10), transparent 26%),
                linear-gradient(180deg, #f8f5ef 0%, var(--bg) 100%);
              color: var(--ink);
              font: 16px/1.55 Georgia, "Iowan Old Style", "Palatino Linotype", serif;
            }
            main {
              width: min(1180px, calc(100vw - 32px));
              margin: 24px auto 48px;
            }
            section, .hero {
              background: color-mix(in srgb, var(--paper) 94%, white);
              border: 1px solid var(--line);
              border-radius: 20px;
              box-shadow: var(--shadow);
              padding: 22px 24px;
              margin-bottom: 18px;
            }
            .hero {
              background:
                linear-gradient(135deg, rgba(23, 76, 60, 0.08), rgba(255, 250, 242, 0.96)),
                var(--paper);
            }
            h1, h2, h3, h4 {
              margin: 0 0 12px;
              line-height: 1.15;
              font-family: "Avenir Next Condensed", "Franklin Gothic Medium", "Arial Narrow", sans-serif;
              letter-spacing: 0.02em;
            }
            h1 { font-size: clamp(2rem, 4vw, 3.4rem); }
            h2 { font-size: 2rem; }
            h3 { font-size: 1.45rem; }
            h4 { font-size: 1.1rem; margin-top: 16px; }
            p { margin: 0 0 12px; color: var(--muted); }
            code, pre { font-family: "SFMono-Regular", "Menlo", "Consolas", monospace; }
            .metrics {
              display: grid;
              grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
              gap: 12px;
              margin-top: 18px;
            }
            .metric {
              padding: 14px 16px;
              border-radius: 16px;
              background: var(--paper-2);
              border: 1px solid var(--line);
            }
            .metric-name {
              display: block;
              color: var(--muted);
              font-size: 0.88rem;
              margin-bottom: 6px;
            }
            details.doc {
              margin-top: 14px;
              border: 1px solid var(--line);
              border-radius: 14px;
              background: rgba(255, 255, 255, 0.5);
              overflow: hidden;
            }
            details.doc > summary {
              cursor: pointer;
              list-style: none;
              padding: 12px 14px;
              font-weight: 700;
              background: var(--paper-2);
            }
            details.doc[open] > summary {
              border-bottom: 1px solid var(--line);
            }
            .doc-body {
              padding: 14px;
            }
            .doc-body > :first-child { margin-top: 0; }
            .distribution-grid {
              display: grid;
              grid-template-columns: minmax(360px, 1.5fr) minmax(260px, 1fr);
              gap: 16px;
              align-items: start;
              margin-top: 12px;
            }
            .chart-card {
              margin: 0;
              padding: 10px;
              border-radius: 16px;
              background: var(--paper-2);
              border: 1px solid var(--line);
            }
            .chart-card figcaption {
              color: var(--muted);
              font-size: 0.9rem;
              padding: 0 6px 4px;
            }
            .chart-bg { fill: rgba(255,255,255,0.65); }
            .axis { stroke: #b39d80; stroke-width: 1; }
            .axis-label { fill: #756954; font-size: 12px; }
            .distribution-line {
              fill: none;
              stroke: var(--accent);
              stroke-width: 3;
              stroke-linecap: round;
              stroke-linejoin: round;
            }
            .threshold-line {
              stroke: var(--warn);
              stroke-width: 1.5;
              stroke-dasharray: 5 5;
            }
            .threshold-point {
              fill: var(--warn);
            }
            .threshold-label {
              fill: var(--warn);
              font-weight: 700;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              background: rgba(255,255,255,0.55);
              border: 1px solid var(--line);
              border-radius: 14px;
              overflow: hidden;
            }
            th, td {
              padding: 9px 12px;
              border-bottom: 1px solid rgba(216, 205, 187, 0.75);
              text-align: left;
              vertical-align: top;
            }
            th {
              background: var(--paper-2);
              font-size: 0.9rem;
            }
            tr:last-child td { border-bottom: none; }
            .over-threshold td {
              color: var(--warn);
              font-weight: 700;
              background: color-mix(in srgb, var(--warn-soft) 45%, white);
            }
            .operation, .gc-block {
              margin-top: 14px;
              padding-top: 12px;
              border-top: 1px solid rgba(216, 205, 187, 0.85);
            }
            .safepoint-entry {
              margin: 0 0 14px;
              padding: 12px 14px;
              border: 1px solid var(--line);
              border-radius: 14px;
              background: rgba(255, 255, 255, 0.45);
            }
            .safepoint-entry p {
              margin-bottom: 10px;
            }
            .log-block {
              margin: 0;
              padding: 14px;
              overflow-x: auto;
              background: #1f241f;
              color: #f3efe6;
            }
            @media (max-width: 900px) {
              main { width: min(100vw - 18px, 100%); margin-top: 10px; }
              section, .hero { padding: 16px; border-radius: 16px; }
              .distribution-grid { grid-template-columns: 1fr; }
            }
            </style>
            </head>
            <body>
            <main>
            """);
    }

    private static void appendPageEnd(StringBuilder html) {
        html.append("</main></body></html>");
    }

    private boolean docExists(Path docPath) throws IOException {
        try (var stream = getClass().getClassLoader().getResourceAsStream(docPath.toString())) {
            return stream != null;
        }
    }

    private String readDoc(Path docPath) throws IOException {
        var strPath = docPath.toString();
        try (var stream = getClass().getClassLoader().getResourceAsStream(strPath)) {
            if (stream == null) {
                throw new IllegalStateException("Can't find document in resources: '%s'".formatted(strPath));
            }
            return new String(stream.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static String renderMarkdown(String markdown) {
        return HTML_RENDERER.render(MARKDOWN_PARSER.parse(markdown));
    }

    private static String escapeHtml(String value) {
        return value
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;");
    }

    @FormatMethod
    private static String format(@FormatString String format, Object... args) {
        return String.format(Locale.ROOT, format, args);
    }
}
