package org.sharpler.glag.output;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import java.util.Map;
import org.fusesource.jansi.AnsiConsole;
import org.sharpler.glag.aggregations.Aggregates;
import org.sharpler.glag.aggregations.SafepointAggregate;

public final class HtmlAggregatesOutput {
    private final Path output;

    public HtmlAggregatesOutput(Path output) {
        this.output = output;
    }

    public void print(Aggregates aggregates, int thresholdMs) throws IOException {
        var aggregate = aggregates.aggregate();
        var writer = new HtmlWriter(new StringBuilder(96 * 1024));

        writer.appendPageStart(getClass(), HtmlWriter.AGGREGATES_PAGE_STYLES_PATH);
        writer.appendOverview(
            aggregate,
            "This report of safepoint log analysis has been generated by <strong>glag</strong> tool version 1.0-SNAPSHOT."
        );
        appendSafepointSection(writer, aggregate, thresholdMs);
        appendOperationsSection(writer, aggregates.aggregatesByType(), thresholdMs);
        writer.appendPageEnd();

        Files.writeString(output, writer.toString());
    }

    private void appendSafepointSection(HtmlWriter writer, SafepointAggregate aggregate, int thresholdMs) throws IOException {
        writer.append("<section>");
        writer.append("<h2>Safepoints</h2>");
        writer.appendDocDetails(getClass(), "What is a safepoint", OutputUtils.DOCS_PATH.resolve("safepoint").resolve("safepoint.md"),
            null);
        writer.appendDistributionSection("Cumulative distribution of total safepoint time", aggregate.totalTimeDistribution(), thresholdMs,
            3);
        writer.appendDistributionSection("Cumulative distribution of time inside a safepoint", aggregate.insideTimeDistribution(),
            thresholdMs, 3);
        writer.appendDistributionSection("Cumulative distribution of cleanup time", aggregate.cleanupTimeDistribution(), thresholdMs, 3);
        writer.appendDistributionSection("Cumulative distribution of time to leave safepoint", aggregate.leavingTimeDistribution(),
            thresholdMs, 3);
        if (aggregate.hasReachingTimeNs()) {
            writer.appendDocDetails(getClass(), "Time to safepoint",
                OutputUtils.DOCS_PATH.resolve("safepoint").resolve("time_to_safepoint.md"), null);
            writer.appendDistributionSection("Cumulative distribution of time to safepoint", aggregate.reachingTimeDistribution(),
                thresholdMs, 3);
        }
        writer.append("</section>");
    }

    private void appendOperationsSection(HtmlWriter writer, Map<String, SafepointAggregate> aggregatesByType, int thresholdMs)
        throws IOException {
        writer.append("<section>");
        writer.append("<h2>JVM operations in safepoint</h2>");

        var unknownOperations = new HashSet<String>();
        for (var e : OutputUtils.sortedOperationAggregates(aggregatesByType)) {
            var operationName = e.getKey();
            var aggregate = e.getValue();

            writer.append("<section class='operation'>");
            writer.append("<h3>Operation <code>").append(writer.escapeHtml(operationName)).append("</code></h3>");
            writer.append("<p>Period: <strong>")
                .append(writer.format("%.3f", aggregate.averagePausePeriodSec()))
                .append("</strong> sec/op</p>");
            if (aggregate.hasInsideTimeNs()) {
                writer.append("<p>Throughput lost due to pauses: <strong>")
                    .append(writer.format("%.3f", aggregate.insideSafepointThroughputLoss()))
                    .append("</strong> % - <strong>")
                    .append(writer.format("%.3f", aggregate.totalPauseThroughputLoss()))
                    .append("</strong> %</p>");
            } else {
                writer.append("<p>Throughput lost due to total pauses: <strong>")
                    .append(writer.format("%.3f", aggregate.totalPauseThroughputLoss()))
                    .append("</strong> %</p>");
            }

            var description = OutputUtils.DOCS_PATH.resolve("operation").resolve(operationName + ".md");
            if (OutputUtils.docExists(getClass(), description)) {
                writer.appendDocDetails(getClass(), "Description", description, null);
            } else if (unknownOperations.add(operationName)) {
                AnsiConsole.err().printf("GC operation '%s' is unknown%n", operationName);
            }

            writer.appendDistributionSection("Cumulative distribution of total time", aggregate.totalTimeDistribution(), thresholdMs, 4);
            writer.appendOptionalAggregateDistributions(aggregate, thresholdMs, 4);
            writer.append("</section>");
        }
        writer.append("</section>");
    }
}
