package org.sharpler.glag.output;

import static java.nio.file.StandardOpenOption.APPEND;

import com.google.errorprone.annotations.FormatMethod;
import com.google.errorprone.annotations.FormatString;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import org.fusesource.jansi.AnsiConsole;
import org.sharpler.glag.aggregations.Aggregates;
import org.sharpler.glag.aggregations.SafepointAggregate;
import org.sharpler.glag.distribution.CumulativeDistributionPoint;

public final class MdAggregatesOutput {
    private static final Path DOCS_PATH = Path.of("docs");

    private final Path output;

    public MdAggregatesOutput(Path output) {
        this.output = output;
    }

    public void print(Aggregates safepoints, int thresholdMs) throws IOException {
        var aggregate = safepoints.aggregate();

        Files.deleteIfExists(output);
        Files.createFile(output);
        writef("# Report%n%n");
        writef("This report of safepoint log analysis has been generated by **glag** tool version 1.0-SNAPSHOT.%n%n");

        if (aggregate.hasInsideTimeNs()) {
            writef(
                "Throughput lost due to pauses: %.3f (%%) - %.3f (%%)%n%n",
                aggregate.insideSafepointThroughputLoss(),
                aggregate.totalPauseThroughputLoss()
            );
        } else {
            writef(
                "Throughput lost due to total pauses: %.3f (%%)%n%n",
                aggregate.totalPauseThroughputLoss()
            );
        }
        writef("Average pause period: %.3f sec/op%n%n", aggregate.averagePausePeriodSec());

        writef("## Safepoints%n%n");
        writeDoc(DOCS_PATH.resolve("safepoint").resolve("safepoint.md"));
        writef("%n%n");
        writeAggregateSection("Total safepoint time", aggregate.totalTimeDistribution(), thresholdMs, 2);
        writeAggregateSection("Time inside a safepoint", aggregate.insideTimeDistribution(), thresholdMs, 2);
        writeAggregateSection("Cleanup time", aggregate.cleanupTimeDistribution(), thresholdMs, 2);
        writeAggregateSection("Time to leave safepoint", aggregate.leavingTimeDistribution(), thresholdMs, 2);

        if (aggregate.hasReachingTimeNs()) {
            writef("## Time to safepoint%n%n");
            writeDoc(DOCS_PATH.resolve("safepoint").resolve("time_to_safepoint.md"));
            writef("%n%n");
            writeAggregateSection("Cumulative distribution", aggregate.reachingTimeDistribution(), thresholdMs, 3);
        }

        writef("## JVM operations in safepoint%n%n");
        var unknownOperations = new HashSet<String>();
        for (var e : sortedOperationAggregates(safepoints)) {
            var operationName = e.getKey();
            var operationAggregate = e.getValue();

            writef("### Operation '%s'%n%n", operationName);
            var description = DOCS_PATH.resolve("operation").resolve(operationName + ".md");
            if (docExists(description)) {
                writef("#### Description%n%n");
                writeDoc(description);
                writef("%n%n");
            } else if (unknownOperations.add(operationName)) {
                AnsiConsole.err().printf("GC operation '%s' is unknown%n", operationName);
            }

            writef("Period: %.3f (sec/op)%n%n", operationAggregate.averagePausePeriodSec());
            if (operationAggregate.hasInsideTimeNs()) {
                writef(
                    "Throughput lost due to pauses: %.3f (%%) - %.3f (%%)%n%n",
                    operationAggregate.insideSafepointThroughputLoss(),
                    operationAggregate.totalPauseThroughputLoss()
                );
            } else {
                writef(
                    "Throughput lost due to total pauses: %.3f (%%)%n%n",
                    operationAggregate.totalPauseThroughputLoss()
                );
            }

            writeAggregateSection("Total time", operationAggregate.totalTimeDistribution(), thresholdMs, 4);
            writeAggregateSection("Time inside a safepoint", operationAggregate.insideTimeDistribution(), thresholdMs, 4);
            writeAggregateSection("Time to safepoint", operationAggregate.reachingTimeDistribution(), thresholdMs, 4);
            writeAggregateSection("Cleanup time", operationAggregate.cleanupTimeDistribution(), thresholdMs, 4);
            writeAggregateSection("Time to leave safepoint", operationAggregate.leavingTimeDistribution(), thresholdMs, 4);
        }
    }

    @FormatMethod
    private void writef(@FormatString String format, Object... args) throws IOException {
        Files.writeString(output, String.format(format, args), APPEND);
    }

    private void writeAggregateSection(
        String title,
        List<CumulativeDistributionPoint> points,
        int thresholdMs,
        int headingLevel
    ) throws IOException {
        if (points.isEmpty()) {
            return;
        }

        writef("%s %s%n%n", "#".repeat(headingLevel), title);
        writef("| Timing (ms) | Probability (%%)|%n");
        writef("| ----------- | -------------- |%n");
        for (var point : points) {
            var timingMs = point.value() / 1E6;
            writef(
                timingMs > thresholdMs ? "| **%.3f** | **%.2f** |%n" : "| %.3f | %.2f |%n",
                timingMs,
                point.prob() * 100d
            );
        }
        writef("%n");
    }

    private static List<Map.Entry<String, SafepointAggregate>> sortedOperationAggregates(Aggregates safepoints) {
        return safepoints.aggregatesByType().entrySet().stream()
            .sorted((left, right) -> Long.compare(right.getValue().totalTimeNsSum(), left.getValue().totalTimeNsSum()))
            .toList();
    }

    private boolean docExists(Path docPath) throws IOException {
        try (var stream = getClass().getClassLoader().getResourceAsStream(docPath.toString())) {
            return stream != null;
        }
    }

    private void writeDoc(Path docPath) throws IOException {
        var strPath = docPath.toString();

        byte[] bytes;
        try (var stream = getClass().getClassLoader().getResourceAsStream(strPath)) {
            if (stream == null) {
                throw new IllegalStateException("Can't find document in resources: '%s'".formatted(strPath));
            }

            bytes = stream.readAllBytes();
        }
        if (bytes.length == 0) {
            throw new IllegalStateException("Can't read document in resources: '%s'".formatted(strPath));
        }
        Files.write(output, bytes, APPEND);
    }
}
