package org.sharpler.glag.output;

import static org.sharpler.glag.output.MdOutputUtils.writeAggregateSection;
import static org.sharpler.glag.output.MdOutputUtils.writeDoc;
import static org.sharpler.glag.output.MdOutputUtils.writef;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import org.fusesource.jansi.AnsiConsole;
import org.sharpler.glag.aggregations.Aggregates;

public final class MdAggregatesOutput {
    private final Path output;

    public MdAggregatesOutput(Path output) {
        this.output = output;
    }

    public void print(Aggregates aggregates, int thresholdMs) throws IOException {
        var aggregate = aggregates.aggregate();

        Files.deleteIfExists(output);
        Files.createFile(output);
        writef(output, "# Report%n%n");
        writef(output, "This report of safepoint log analysis has been generated by **glag** tool version 1.0-SNAPSHOT.%n%n");

        if (aggregate.hasInsideTimeNs()) {
            writef(
                output,
                "Throughput lost due to pauses: %.3f (%%) - %.3f (%%)%n%n",
                aggregate.insideSafepointThroughputLoss(),
                aggregate.totalPauseThroughputLoss()
            );
        } else {
            writef(
                output,
                "Throughput lost due to total pauses: %.3f (%%)%n%n",
                aggregate.totalPauseThroughputLoss()
            );
        }
        writef(output, "Average pause period: %.3f sec/op%n%n", aggregate.averagePausePeriodSec());

        writef(output, "## Safepoints%n%n");
        writeDoc(output, getClass(), OutputUtils.DOCS_PATH.resolve("safepoint").resolve("safepoint.md"));
        writef(output, "%n%n");
        writeAggregateSection(output, "Total safepoint time", aggregate.totalTimeDistribution(), thresholdMs, 2);
        writeAggregateSection(output, "Time inside a safepoint", aggregate.insideTimeDistribution(), thresholdMs, 2);
        writeAggregateSection(output, "Cleanup time", aggregate.cleanupTimeDistribution(), thresholdMs, 2);
        writeAggregateSection(output, "Time to leave safepoint", aggregate.leavingTimeDistribution(), thresholdMs, 2);

        if (aggregate.hasReachingTimeNs()) {
            writef(output, "## Time to safepoint%n%n");
            writeDoc(output, getClass(), OutputUtils.DOCS_PATH.resolve("safepoint").resolve("time_to_safepoint.md"));
            writef(output, "%n%n");
            writeAggregateSection(output, "Cumulative distribution", aggregate.reachingTimeDistribution(), thresholdMs, 3);
        }

        writef(output, "## JVM operations in safepoint%n%n");
        var unknownOperations = new HashSet<String>();
        for (var e : OutputUtils.sortedOperationAggregates(aggregates.aggregatesByType())) {
            var operationName = e.getKey();
            var operationAggregate = e.getValue();

            writef(output, "### Operation '%s'%n%n", operationName);
            var description = OutputUtils.DOCS_PATH.resolve("operation").resolve(operationName + ".md");
            if (OutputUtils.docExists(getClass(), description)) {
                writef(output, "#### Description%n%n");
                writeDoc(output, getClass(), description);
                writef(output, "%n%n");
            } else if (unknownOperations.add(operationName)) {
                AnsiConsole.err().printf("GC operation '%s' is unknown%n", operationName);
            }

            writef(output, "Period: %.3f (sec/op)%n%n", operationAggregate.averagePausePeriodSec());
            if (operationAggregate.hasInsideTimeNs()) {
                writef(
                    output,
                    "Throughput lost due to pauses: %.3f (%%) - %.3f (%%)%n%n",
                    operationAggregate.insideSafepointThroughputLoss(),
                    operationAggregate.totalPauseThroughputLoss()
                );
            } else {
                writef(
                    output,
                    "Throughput lost due to total pauses: %.3f (%%)%n%n",
                    operationAggregate.totalPauseThroughputLoss()
                );
            }

            writeAggregateSection(output, "Total time", operationAggregate.totalTimeDistribution(), thresholdMs, 4);
            writeAggregateSection(output, "Time inside a safepoint", operationAggregate.insideTimeDistribution(), thresholdMs, 4);
            writeAggregateSection(output, "Time to safepoint", operationAggregate.reachingTimeDistribution(), thresholdMs, 4);
            writeAggregateSection(output, "Cleanup time", operationAggregate.cleanupTimeDistribution(), thresholdMs, 4);
            writeAggregateSection(output, "Time to leave safepoint", operationAggregate.leavingTimeDistribution(), thresholdMs, 4);
        }
    }
}
