package org.sharpler.glag.output;

import static org.sharpler.glag.output.MdOutputUtils.writeAggregateSection;
import static org.sharpler.glag.output.MdOutputUtils.writeDoc;
import static org.sharpler.glag.output.MdOutputUtils.writef;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import org.fusesource.jansi.AnsiConsole;
import org.sharpler.glag.aggregations.RuntimeEvents;
import org.sharpler.glag.records.GcIteration;
import org.sharpler.glag.records.SafepointLogRecord;
import org.sharpler.glag.records.SingleVMOperation;
import org.sharpler.glag.util.TimeUtils;

public final class MdOutput {
    private final Path output;

    public MdOutput(Path output) {
        this.output = output;
    }

    public void print(RuntimeEvents runtimeEvents, int examples) throws IOException {
        var thresholdMs = runtimeEvents.thresholdMs();
        var safepoints = runtimeEvents.safepointLog();
        var aggregate = safepoints.aggregate();

        Files.deleteIfExists(output);
        Files.createFile(output);
        writef(output, "# Report%n%n");
        writef(output, "This report of gc and safepoint log analysis has been generated by **glag** tool version 1.0-SNAPSHOT.%n%n");

        if (aggregate.hasInsideTimeNs()) {
            writef(
                output,
                "Throughput lost due to pauses: %.3f (%%) - %.3f (%%)%n%n",
                aggregate.insideSafepointThroughputLoss(),
                aggregate.totalPauseThroughputLoss()
            );
        } else {
            writef(
                output,
                "Throughput lost due to total pauses: %.3f (%%)%n%n",
                aggregate.totalPauseThroughputLoss()
            );
        }
        writef(output, "Average pause period: %.3f sec/op%n%n", aggregate.averagePausePeriodSec());

        if (runtimeEvents.gcName() != null) {
            var name = runtimeEvents.gcName().getName();
            writef(output, "%s has been detected.%n%n", name);
            var gcDescription = OutputUtils.DOCS_PATH.resolve("gc").resolve(name + ".md");
            if (OutputUtils.docExists(getClass(), gcDescription)) {
                writef(output, "## %s%n%n", name);
                writeDoc(output, getClass(), gcDescription);
                writef(output, "%n%n");
            } else {
                AnsiConsole.err().printf("GC '%s' description is unsupported%n", name);
            }
        } else {
            AnsiConsole.err().println("Failed to detect GC by logs");
        }

        writef(output, "## Safepoints%n%n");
        writeDoc(output, getClass(), OutputUtils.DOCS_PATH.resolve("safepoint").resolve("safepoint.md"));
        writef(output, "%n%n");
        writeAggregateSection(output, "Total safepoint time", safepoints.aggregate().totalTimeDistribution(), thresholdMs, 2);
        writeAggregateSection(output, "Time inside a safepoint", safepoints.aggregate().insideTimeDistribution(), thresholdMs, 2);
        writeAggregateSection(output, "Cleanup time", safepoints.aggregate().cleanupTimeDistribution(), thresholdMs, 2);
        writeAggregateSection(output, "Time to leave safepoint", safepoints.aggregate().leavingTimeDistribution(), thresholdMs, 2);
        writef(output, "## JVM operations in safepoint%n%n");

        var unknownOperations = new HashSet<String>();
        for (var e : OutputUtils.sortedOperationAggregates(safepoints.aggregatesByType())) {
            var operationName = e.getKey();
            var operationAggregate = e.getValue();

            writef(output, "### Operation '%s'%n%n", operationName);
            var description = OutputUtils.DOCS_PATH.resolve("operation").resolve(operationName + ".md");
            if (OutputUtils.docExists(getClass(), description)) {
                writef(output, "#### Description%n%n");
                writeDoc(output, getClass(), description);
                writef(output, "%n%n");
            } else {
                if (unknownOperations.add(operationName)) {
                    AnsiConsole.err().printf("GC operation '%s' is unknown%n", operationName);
                }
            }

            writef(output, "Period: %.3f (sec/op)%n%n", operationAggregate.averagePausePeriodSec());
            if (operationAggregate.hasInsideTimeNs()) {
                writef(
                    output,
                    "Throughput lost due to pauses: %.3f (%%) - %.3f (%%)%n%n",
                    operationAggregate.insideSafepointThroughputLoss(),
                    operationAggregate.totalPauseThroughputLoss()
                );
            } else {
                writef(
                    output,
                    "Throughput lost due to total pauses: %.3f (%%)%n%n",
                    operationAggregate.totalPauseThroughputLoss()
                );
            }
            writeAggregateSection(output, "Total time", operationAggregate.totalTimeDistribution(), thresholdMs, 4);
            writeAggregateSection(output, "Time inside a safepoint", operationAggregate.insideTimeDistribution(), thresholdMs, 4);
            writeAggregateSection(output, "Time to safepoint", operationAggregate.reachingTimeDistribution(), thresholdMs, 4);
            writeAggregateSection(output, "Cleanup time", operationAggregate.cleanupTimeDistribution(), thresholdMs, 4);
            writeAggregateSection(output, "Time to leave safepoint", operationAggregate.leavingTimeDistribution(), thresholdMs, 4);

            var slowSingleVmOperations = runtimeEvents.slowSingleVmOperations().getOrDefault(operationName, List.of());

            if (slowSingleVmOperations.isEmpty()) {
                continue;
            }

            var topSlowVmOperations = slowSingleVmOperations
                .stream()
                .map(SingleVMOperation::safepointLog)
                .sorted(Comparator.comparingLong(SafepointLogRecord::totalTimeNs).reversed())
                .limit(examples)
                .toList();

            if (!topSlowVmOperations.isEmpty()) {
                writef(output, "#### Slow individual safepoints: threshold = %d ms, top %d%n%n", thresholdMs, examples);
                writef(output, "```");
                for (var safepointLog : topSlowVmOperations) {
                    writef(output, "%n%s%n", safepointLog.origin());
                }
                writef(output, "```%n%n");
            }
        }

        if (aggregate.hasReachingTimeNs()) {
            writef(output, "## Time to safepoint%n%n");
            writeDoc(output, getClass(), OutputUtils.DOCS_PATH.resolve("safepoint").resolve("time_to_safepoint.md"));
            writef(output, "%n%n");
            writeAggregateSection(output, "Cumulative distribution", aggregate.reachingTimeDistribution(), thresholdMs, 3);
        }

        var slowGcs = runtimeEvents.slowGcs()
            .stream()
            .sorted(Comparator.comparingDouble((GcIteration x) -> x.gcLog().finishTimeSec() - x.gcLog().startTimeSec()).reversed())
            .limit(examples)
            .toList();
        if (!slowGcs.isEmpty()) {
            writef(output, "## GC iterations with long pauses: threshold = %d ms, top %d%n%n", thresholdMs, examples);

            for (var slowGc : slowGcs) {
                writef(
                    output,
                    "### GC iteration %d (%s)%n%n",
                    slowGc.gcLog().gcNum(),
                    TimeUtils.formatDuration(Math.round((slowGc.gcLog().finishTimeSec() - slowGc.gcLog().startTimeSec()) * 1E9))
                );

                writef(output, "#### Slow safepoints%n%n");
                writef(output, "```");
                for (var safepoint : slowGc.safepointLog()) {
                    writef(output, "%n%s%n", safepoint.origin());
                }
                writef(output, "```%n%n");

                writef(output, "#### Gc logs%n%n");
                writef(output, "```%n");
                for (var gcEvent : slowGc.gcLog().records()) {
                    writef(output, "%s%n", gcEvent.origin());
                }
                writef(output, "```%n%n");
            }
        }
        var slowSimultaneousGcs = runtimeEvents.slowSimultaneousGcs();
        if (!slowSimultaneousGcs.isEmpty()) {
            writef(output, "## Simultaneous GC iterations with long pauses: threshold = %d ms%n%n", thresholdMs);

            for (var slowSimultaneousGc : slowSimultaneousGcs) {
                writef(
                    output,
                    "### GC iterations %s%n%n",
                    slowSimultaneousGc.gcs().stream()
                        .map(gc -> "%d (%s)".formatted(
                            gc.gcNum(),
                            TimeUtils.formatDuration(Math.round((gc.finishTimeSec() - gc.startTimeSec()) * 1E9))
                        ))
                        .toList()
                );

                writef(output, "#### Slow safepoints%n%n");
                writef(output, "```");
                for (var safepoint : slowSimultaneousGc.safepointLog()) {
                    writef(output, "%n%s%n", safepoint.origin());
                }
                writef(output, "```%n");


                for (var slowGc : slowSimultaneousGc.gcs()) {
                    writef(output, "#### GC %d logs%n%n", slowGc.gcNum());
                    writef(output, "```%n");
                    for (var gcEvent : slowGc.records()) {
                        writef(output, "%s%n", gcEvent.origin());
                    }
                    writef(output, "```%n%n");
                }
            }
        }

    }
}
