package org.sharpler.glag.output;

import static java.nio.file.StandardOpenOption.APPEND;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.sharpler.glag.aggregations.GcLog;
import org.sharpler.glag.aggregations.SafapointLog;
import org.sharpler.glag.distribution.CumulativeDistributionBuilder;
import org.sharpler.glag.records.SafepointEvent;
import org.sharpler.glag.records.SafepointExplain;

public final class MdOutput {
    private static final Path DOCS_PATH = Paths.get("src", "main", "resources", "docs");

    private final Path output;

    public MdOutput(Path output) {
        this.output = output;
    }

    public void print(SafapointLog safepoints, GcLog gcLog, int thresholdMs) throws IOException {
        Files.deleteIfExists(output);
        Files.createFile(output);
        writef("# Report%n%n");
        writef("This report of gc and safepoint log analysis has been generated by **glag** tool version 1.0-SNAPSHOT.%n%n");

        if (gcLog.gcName() != null) {
            var name = gcLog.gcName().getName();
            writef("%s has been detected.%n%n", name);
            var gcDescription = DOCS_PATH.resolve("gc").resolve(name + ".md");
            if (Files.exists(gcDescription)) {
                writef("## %s%n%n", name);
                writeDoc(gcDescription);
                writef("%n%n");
            }
        }

        writef("## Safepoints%n%n");
        writeDoc(DOCS_PATH.resolve("safepoint").resolve("safepoint.md"));
        writef("%n%n");
        writef("## JVM operations in safepoint%n%n");

        for (var e : safepoints.distributions().entrySet()) {
            var events = safepoints.events().get(e.getKey());

            writef("### Operation '%s'%n%n", e.getKey());
            var description = DOCS_PATH.resolve("operation").resolve(e.getKey() + ".md");
            if (Files.exists(description)) {
                writef("#### Description%n%n");
                writeDoc(description);
                writef("%n%n");
            }

            writef(
                "Frequency: %.3f op/min%n%n",
                60d * events.size() / (safepoints.finishLogSec() - safepoints.startLogSec())
            );

            writef("#### Cumulative distribution:%n%n");

            writef("| Timing (ms) | Probability (%%)|%n");
            writef("| ----------- | -------------- |%n");
            for (var point : e.getValue()) {
                var timingMs = point.value() / 1E6;

                writef(
                    timingMs > thresholdMs ?
                        "| **%.3f** | **%.2f** |%n" :
                        "| %.3f | %.2f |%n",
                    timingMs,
                    point.prob() * 100d
                );
            }

            if (e.getValue().get(e.getValue().size() - 1).value() / 1E6 < thresholdMs) {
                continue;
            }

            writef("#### Slow events: threshold = %d (ms)%n%n", thresholdMs);

            var explains = events.stream()
                .filter(event -> event.insideTimeNs() > TimeUnit.MILLISECONDS.toNanos(thresholdMs))
                .map(x -> tryExplain(x, gcLog))
                .collect(
                    Collectors.partitioningBy(x -> x.explain instanceof SafepointExplain.NoExplain)
                );

            for (var explain : explains.get(false)) {
                writef("##### Slow safepoint : safepoint log line = %d%n%n", explain.event().line());
                writef("Operation time = %d (ns)%n%n", explain.event().insideTimeNs());
                writef("Time to safepoint = %d (ns)%n%n", explain.event.reachingTimeNs());

                if (explain.explain() instanceof SafepointExplain.GcExplain) {
                    var gcExplain = (SafepointExplain.GcExplain) explain.explain();
                    writef("Found following gc operation: %s %n%n", gcExplain.gcs().keySet());

                    for (var gc : gcExplain.gcs().entrySet()) {
                        writef("###### GC invocation = %d%n%n", gc.getKey());
                        writef("```%n");
                        for (var gcEvent : gc.getValue()) {
                            writef("%s%n", gcEvent.origin());
                        }
                        writef("```%n%n");
                    }
                }
            }

            writef("##### Slow safepoint without explain%n%n");


            writef("| line in safepoint log | operation time (ns)| time to safepoint (ns) |%n");
            writef("| --------------------- | ------------------ | ---------------------- |%n");

            for (var event : explains.get(true)) {
                if (event.event().insideTimeNs() > TimeUnit.MILLISECONDS.toNanos(thresholdMs)) {
                    writef(
                        "| %d | %d | %d | ",
                        event.event().line(),
                        event.event().insideTimeNs(),
                        event.event().reachingTimeNs()
                    );
                }
            }
        }

        writef("## Time to safepoint%n%n");

        writeDoc(DOCS_PATH.resolve("safepoint").resolve("time_to_safepoint.md"));

        writef("%n%n");

        writef("### Cumulative distribution%n%n");

        writef("| Timing (ms) | Probability (%%)|%n");
        writef("| ----------- | -------------- |%n");

        for (var point : CumulativeDistributionBuilder.reachingDistribution(safepoints)) {
            var timingMs = point.value() / 1E6;
            writef(
                timingMs > thresholdMs ?
                    "| **%.3f** | **%.2f** |%n" :
                    "| %.3f | %.2f |%n",
                timingMs,
                point.prob() * 100d
            );
        }
    }

    private SafepointWithExplain tryExplain(SafepointEvent event, GcLog gcLog) {
        if (event.timestampSec() < gcLog.startLogSec() || event.timestampSec() > gcLog.finishLogSec()) {
            return new SafepointWithExplain(event, SafepointExplain.NoExplain.INSTANCE);
        }

        var gcNums = gcLog.findGcByTime(event.timestampSec(), 0.1d);
        if (gcNums.isEmpty()) {
            return new SafepointWithExplain(event, SafepointExplain.NoExplain.INSTANCE);
        }

        return new SafepointWithExplain(
            event,
            new SafepointExplain.GcExplain(gcNums.stream().collect(Collectors.toMap(Function.identity(), x -> gcLog.events().get(x))))
        );
    }

    private record SafepointWithExplain(SafepointEvent event, SafepointExplain explain) {

    }

    private void writef(String format, Object... args) throws IOException {
        Files.writeString(output, String.format(format, args), APPEND);
    }

    private void writeDoc(Path docPath) throws IOException {
        Files.write(output, Files.readAllBytes(docPath), APPEND);
    }
}
