package io.github.sharpler.glag.output.html;

import io.github.sharpler.glag.aggregations.GcIteration;
import io.github.sharpler.glag.aggregations.RuntimeEvents;
import io.github.sharpler.glag.aggregations.SafepointAggregate;
import io.github.sharpler.glag.aggregations.SingleVMOperation;
import io.github.sharpler.glag.output.OutputUtils;
import io.github.sharpler.glag.output.RenderResult;
import io.github.sharpler.glag.records.GcLogRecords;
import io.github.sharpler.glag.records.GcName;
import io.github.sharpler.glag.records.SafepointLogRecord;
import io.github.sharpler.glag.util.TimeUtils;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import org.jspecify.annotations.Nullable;

/// Writes the full HTML report with GC correlation.
public final class HtmlFullOutput {
    /// Prevents instantiation of this utility class.
    private HtmlFullOutput() {}

    /// Renders an HTML report for correlated runtime events.
    ///
    /// @param runtimeEvents correlated GC and safepoint events
    /// @param examples number of slow examples to include in each section
    /// @return rendered report and non-fatal rendering errors
    /// @throws IOException if embedded documentation or styles cannot be read
    public static RenderResult render(RuntimeEvents runtimeEvents, int examples) throws IOException {
        var thresholdMs = runtimeEvents.thresholdMs();
        var safepoints = runtimeEvents.safepointLog();
        var aggregate = safepoints.aggregate();
        var errors = new ArrayList<String>();
        var writer = new HtmlWriter(new StringBuilder(128 * 1024), errors);

        writer.appendPageStart(HtmlFullOutput.class, HtmlWriter.FULL_PAGE_STYLES_PATH);
        writer.appendOverview(
            aggregate,
            "This report of gc and safepoint log analysis has been generated by <strong>glag</strong> tool version 1.0-SNAPSHOT."
        );
        appendGcSection(writer, runtimeEvents.gcName());
        appendSafepointSection(writer, safepoints.aggregate(), thresholdMs);
        appendOperationsSection(writer, runtimeEvents, examples);
        appendTimeToSafepointSection(writer, safepoints.aggregate(), thresholdMs);
        appendSlowGcSections(writer, runtimeEvents, examples);
        writer.appendPageEnd();

        return new RenderResult(writer.toString(), errors);
    }

    private static void appendGcSection(HtmlWriter writer, @Nullable GcName gcName) throws IOException {
        writer.append("<section>");
        writer.append("<h2>GC</h2>");
        if (gcName != null) {
            var name = gcName.getName();
            writer.append("<p><strong>").append(writer.escapeHtml(name)).append("</strong> has been detected.</p>");
            writer.appendDocDetails(HtmlFullOutput.class, "GC description", OutputUtils.DOCS_PATH.resolve("gc").resolve(name + ".md"),
                "GC '%s' description is unsupported".formatted(name));
        } else {
            writer.append("<p>Failed to detect GC by logs.</p>");
            writer.addError("Failed to detect GC by logs");
        }
        writer.append("</section>");
    }

    private static void appendSafepointSection(HtmlWriter writer, SafepointAggregate aggregate, int thresholdMs) throws IOException {
        writer.append("<section>");
        writer.append("<h2>Safepoints</h2>");
        writer.appendDocDetails(
            HtmlFullOutput.class,
            "What is a safepoint",
            OutputUtils.DOCS_PATH.resolve("safepoint").resolve("safepoint.md"),
            null
        );
        writer.appendDistributionSection("Cumulative distribution of total safepoint time", aggregate.totalTimeDistribution(),
            thresholdMs, 3);
        writer.appendDistributionSection("Cumulative distribution of time inside a safepoint",
            aggregate.insideTimeDistribution(), thresholdMs, 3);
        writer.appendDistributionSection("Cumulative distribution of cleanup time", aggregate.cleanupTimeDistribution(),
            thresholdMs, 3);
        writer.appendDistributionSection("Cumulative distribution of time to leave safepoint",
            aggregate.leavingTimeDistribution(), thresholdMs, 3);
        writer.append("</section>");
    }

    private static void appendOperationsSection(HtmlWriter writer, RuntimeEvents runtimeEvents, int examples) throws IOException {
        var safepoints = runtimeEvents.safepointLog();
        var thresholdMs = runtimeEvents.thresholdMs();

        writer.append("<section>");
        writer.append("<h2>JVM operations in safepoint</h2>");

        var unknownOperations = new HashSet<String>();
        for (var e : OutputUtils.sortedOperationAggregates(safepoints.aggregatesByType())) {
            var operationName = e.getKey();
            var operationAggregate = e.getValue();

            writer.append("<section class='operation'>");
            writer.append("<h3>Operation <code>").append(writer.escapeHtml(operationName)).append("</code></h3>");
            writer.append("<p>Period: <strong>")
                .append(writer.format("%.3f", operationAggregate.averagePausePeriodSec()))
                .append("</strong> sec/op</p>");
            if (operationAggregate.hasInsideTimeNs()) {
                writer.append("<p>Throughput lost due to pauses: <strong>")
                    .append(writer.format("%.3f", operationAggregate.insideSafepointThroughputLoss()))
                    .append("</strong> % - <strong>")
                    .append(writer.format("%.3f", operationAggregate.totalPauseThroughputLoss()))
                    .append("</strong> %</p>");
            } else {
                writer.append("<p>Throughput lost due to total pauses: <strong>")
                    .append(writer.format("%.3f", operationAggregate.totalPauseThroughputLoss()))
                    .append("</strong> %</p>");
            }

            var description = OutputUtils.DOCS_PATH.resolve("operation").resolve(operationName + ".md");
            if (OutputUtils.docExists(HtmlFullOutput.class, description)) {
                writer.appendDocDetails(HtmlFullOutput.class, "Description", description, null);
            } else if (unknownOperations.add(operationName)) {
                writer.addError("GC operation '%s' is unknown".formatted(operationName));
            }

            writer.appendDistributionSection("Cumulative distribution of total time", operationAggregate.totalTimeDistribution(),
                thresholdMs, 4);
            writer.appendOptionalAggregateDistributions(operationAggregate, thresholdMs, 4);

            var slowSingleVmOperations = runtimeEvents.slowSingleVmOperations().getOrDefault(operationName, List.of());
            if (!slowSingleVmOperations.isEmpty()) {
                writer.append("<h4>Slow single safepoints</h4>");
                writer.append("<p>threshold = ").append(runtimeEvents.thresholdMs()).append(" ms, top ").append(examples).append("</p>");

                var topSlowVmOperations = slowSingleVmOperations
                    .stream()
                    .map(SingleVMOperation::safepointLog)
                    .sorted(Comparator.comparingLong(SafepointLogRecord::totalTimeNs).reversed())
                    .limit(examples)
                    .toList();

                for (var safepointLog : topSlowVmOperations) {
                    appendSafepointEntry(writer, safepointLog, false);
                }
            }
            writer.append("</section>");
        }
        writer.append("</section>");
    }

    private static void appendTimeToSafepointSection(HtmlWriter writer, SafepointAggregate aggregate, int thresholdMs)
        throws IOException {
        if (!aggregate.hasReachingTimeNs()) {
            return;
        }
        writer.append("<section>");
        writer.append("<h2>Time to safepoint</h2>");
        writer.appendDocDetails(HtmlFullOutput.class, "Description",
            OutputUtils.DOCS_PATH.resolve("safepoint").resolve("time_to_safepoint.md"),
            null);
        writer.appendDistributionSection(
            "Cumulative distribution",
            aggregate.reachingTimeDistribution(),
            thresholdMs,
            2
        );
        writer.append("</section>");
    }

    private static void appendSlowGcSections(HtmlWriter writer, RuntimeEvents runtimeEvents, int examples) {
        var slowGcs = runtimeEvents.slowGcs()
            .stream()
            .sorted(Comparator.comparingDouble((GcIteration x) -> x.gcLog().finishTimeSec() - x.gcLog().startTimeSec()).reversed())
            .limit(examples)
            .toList();
        if (!slowGcs.isEmpty()) {
            writer.append("<section>");
            writer.append("<h2>GC iterations with long pauses</h2>");
            writer.append("<p>threshold = ").append(runtimeEvents.thresholdMs()).append(" ms, top ").append(examples).append("</p>");
            for (var slowGc : slowGcs) {
                writer.append("<section class='gc-block'>");
                writer.append("<h3>GC iteration ")
                    .append(slowGc.gcLog().gcNum())
                    .append(" (")
                    .append(writer.escapeHtml(
                        TimeUtils.formatDuration(Math.round((slowGc.gcLog().finishTimeSec() - slowGc.gcLog().startTimeSec()) * 1E9))))
                    .append(")</h3>");
                appendSafepointList(writer, slowGc.safepointLog());
                appendGcLogs(writer, "GC logs", slowGc.gcLog());
                writer.append("</section>");
            }
            writer.append("</section>");
        }

        var slowSimultaneousGcs = runtimeEvents.slowSimultaneousGcs();
        if (!slowSimultaneousGcs.isEmpty()) {
            writer.append("<section>");
            writer.append("<h2>Simultaneous GC iterations with long pauses</h2>");
            writer.append("<p>threshold = ").append(runtimeEvents.thresholdMs()).append(" ms</p>");
            for (var slowSimultaneousGc : slowSimultaneousGcs) {
                writer.append("<section class='gc-block'>");
                writer.append("<h3>GC iterations ")
                    .append(writer.escapeHtml(slowSimultaneousGc.gcs().stream()
                        .map(gc -> "%d (%s)".formatted(
                            gc.gcNum(),
                            TimeUtils.formatDuration(Math.round((gc.finishTimeSec() - gc.startTimeSec()) * 1E9))
                        ))
                        .toList()
                        .toString()))
                    .append("</h3>");
                appendSafepointList(writer, slowSimultaneousGc.safepointLog());
                for (var slowGc : slowSimultaneousGc.gcs()) {
                    appendGcLogs(writer, "GC %d logs".formatted(slowGc.gcNum()), slowGc);
                }
                writer.append("</section>");
            }
            writer.append("</section>");
        }
    }

    private static void appendSafepointList(HtmlWriter writer, List<SafepointLogRecord> safepoints) {
        writer.append("<h4>Slow safepoints</h4>");
        for (var safepoint : safepoints) {
            appendSafepointEntry(writer, safepoint, true);
        }
    }

    private static void appendGcLogs(HtmlWriter writer, String title, GcLogRecords gcLog) {
        writer.append("<details class='doc'><summary>").append(writer.escapeHtml(title)).append("</summary>");
        writer.append("<pre class='log-block'>");
        for (var gcEvent : gcLog.records()) {
            writer.append(writer.escapeHtml(gcEvent.origin())).append('\n');
        }
        writer.append("</pre></details>");
    }

    private static void appendSafepointEntry(HtmlWriter writer, SafepointLogRecord safepoint, boolean includeOperationName) {
        writer.append("<details class='doc safepoint-entry'><summary>");
        if (includeOperationName) {
            writer.append("operation = ").append(writer.escapeHtml(safepoint.operationName())).append(", ");
        }
        writer.append("total time = ").append(TimeUtils.formatDuration(safepoint.totalTimeNs())).append("</summary>");
        writer.append("<pre class='log-block'>").append(writer.escapeHtml(safepoint.origin())).append("</pre>");
        writer.append("</details>");
    }
}
