package org.sharpler.glag.output.md;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import org.sharpler.glag.aggregations.Aggregates;
import org.sharpler.glag.output.OutputUtils;
import org.sharpler.glag.output.RenderResult;

/// Writes a Markdown report that only depends on safepoint aggregates.
public final class MdAggregatesOutput {
    /// Prevents instantiation of this utility class.
    private MdAggregatesOutput() {}

    /// Renders a Markdown report for safepoint aggregates.
    ///
    /// @param aggregates overall and per-operation safepoint aggregates
    /// @param thresholdMs threshold used when rendering distributions
    /// @return rendered report and non-fatal rendering errors
    /// @throws IOException if embedded documentation cannot be read
    public static RenderResult render(Aggregates aggregates, int thresholdMs) throws IOException {
        var aggregate = aggregates.aggregate();
        var writer = new MdWriter(new StringBuilder(64 * 1024));

        writer.writef("# Report%n%n");
        writer.writef("This report of safepoint log analysis has been generated by **glag** tool version 1.0-SNAPSHOT.%n%n");

        if (aggregate.hasInsideTimeNs()) {
            writer.writef(
                "Throughput lost due to pauses: %.3f (%%) - %.3f (%%)%n%n",
                aggregate.insideSafepointThroughputLoss(),
                aggregate.totalPauseThroughputLoss()
            );
        } else {
            writer.writef(
                "Throughput lost due to total pauses: %.3f (%%)%n%n",
                aggregate.totalPauseThroughputLoss()
            );
        }
        writer.writef("Average pause period: %.3f sec/op%n%n", aggregate.averagePausePeriodSec());

        writer.writef("## Safepoints%n%n");
        writer.writeDoc(MdAggregatesOutput.class, OutputUtils.DOCS_PATH.resolve("safepoint").resolve("safepoint.md"));
        writer.writef("%n%n");
        writer.writeAggregateSection("Total safepoint time", aggregate.totalTimeDistribution(), thresholdMs, 2);
        writer.writeAggregateSection("Time inside a safepoint", aggregate.insideTimeDistribution(), thresholdMs, 2);
        writer.writeAggregateSection("Cleanup time", aggregate.cleanupTimeDistribution(), thresholdMs, 2);
        writer.writeAggregateSection("Time to leave safepoint", aggregate.leavingTimeDistribution(), thresholdMs, 2);

        if (aggregate.hasReachingTimeNs()) {
            writer.writef("## Time to safepoint%n%n");
            writer.writeDoc(MdAggregatesOutput.class, OutputUtils.DOCS_PATH.resolve("safepoint").resolve("time_to_safepoint.md"));
            writer.writef("%n%n");
            writer.writeAggregateSection("Cumulative distribution", aggregate.reachingTimeDistribution(), thresholdMs, 3);
        }

        writer.writef("## JVM operations in safepoint%n%n");
        var errors = new ArrayList<String>();
        var unknownOperations = new HashSet<String>();
        for (var e : OutputUtils.sortedOperationAggregates(aggregates.aggregatesByType())) {
            var operationName = e.getKey();
            var operationAggregate = e.getValue();

            writer.writef("### Operation '%s'%n%n", operationName);
            var description = OutputUtils.DOCS_PATH.resolve("operation").resolve(operationName + ".md");
            if (OutputUtils.docExists(MdAggregatesOutput.class, description)) {
                writer.writef("#### Description%n%n");
                writer.writeDoc(MdAggregatesOutput.class, description);
                writer.writef("%n%n");
            } else if (unknownOperations.add(operationName)) {
                errors.add("GC operation '%s' is unknown".formatted(operationName));
            }

            writer.writef("Period: %.3f (sec/op)%n%n", operationAggregate.averagePausePeriodSec());
            if (operationAggregate.hasInsideTimeNs()) {
                writer.writef(
                    "Throughput lost due to pauses: %.3f (%%) - %.3f (%%)%n%n",
                    operationAggregate.insideSafepointThroughputLoss(),
                    operationAggregate.totalPauseThroughputLoss()
                );
            } else {
                writer.writef(
                    "Throughput lost due to total pauses: %.3f (%%)%n%n",
                    operationAggregate.totalPauseThroughputLoss()
                );
            }

            writer.writeAggregateSection("Total time", operationAggregate.totalTimeDistribution(), thresholdMs, 4);
            writer.writeAggregateSection("Time inside a safepoint", operationAggregate.insideTimeDistribution(), thresholdMs, 4);
            writer.writeAggregateSection("Time to safepoint", operationAggregate.reachingTimeDistribution(), thresholdMs, 4);
            writer.writeAggregateSection("Cleanup time", operationAggregate.cleanupTimeDistribution(), thresholdMs, 4);
            writer.writeAggregateSection("Time to leave safepoint", operationAggregate.leavingTimeDistribution(), thresholdMs, 4);
        }

        return new RenderResult(writer.toString(), errors);
    }
}
