package org.sharpler.glag.output.md;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import org.fusesource.jansi.AnsiConsole;
import org.sharpler.glag.aggregations.GcIteration;
import org.sharpler.glag.aggregations.RuntimeEvents;
import org.sharpler.glag.aggregations.SingleVMOperation;
import org.sharpler.glag.output.OutputUtils;
import org.sharpler.glag.records.SafepointLogRecord;
import org.sharpler.glag.util.TimeUtils;

/// Writes the full Markdown report with GC correlation.
public final class MdFullOutput {
    private final Path output;

    /// Creates a Markdown writer targeting `output`.
    ///
    /// @param output destination Markdown file
    public MdFullOutput(Path output) {
        this.output = output;
    }

    /// Writes a Markdown report for correlated runtime events.
    ///
    /// @param runtimeEvents correlated GC and safepoint events
    /// @param examples number of slow examples to include in each section
    /// @throws IOException if the output file cannot be written
    public void print(RuntimeEvents runtimeEvents, int examples) throws IOException {
        var safepoints = runtimeEvents.safepointLog();
        var aggregate = safepoints.aggregate();
        var writer = new MdWriter(new StringBuilder(128 * 1024));

        writer.writef("# Report%n%n");
        writer.writef("This report of gc and safepoint log analysis has been generated by **glag** tool version 1.0-SNAPSHOT.%n%n");

        if (aggregate.hasInsideTimeNs()) {
            writer.writef(
                "Throughput lost due to pauses: %.3f (%%) - %.3f (%%)%n%n",
                aggregate.insideSafepointThroughputLoss(),
                aggregate.totalPauseThroughputLoss()
            );
        } else {
            writer.writef(
                "Throughput lost due to total pauses: %.3f (%%)%n%n",
                aggregate.totalPauseThroughputLoss()
            );
        }
        writer.writef("Average pause period: %.3f sec/op%n%n", aggregate.averagePausePeriodSec());

        if (runtimeEvents.gcName() != null) {
            var name = runtimeEvents.gcName().getName();
            writer.writef("%s has been detected.%n%n", name);
            var gcDescription = OutputUtils.DOCS_PATH.resolve("gc").resolve(name + ".md");
            if (OutputUtils.docExists(getClass(), gcDescription)) {
                writer.writef("## %s%n%n", name);
                writer.writeDoc(getClass(), gcDescription);
                writer.writef("%n%n");
            } else {
                AnsiConsole.err().printf("GC '%s' description is unsupported%n", name);
            }
        } else {
            AnsiConsole.err().println("Failed to detect GC by logs");
        }

        var thresholdMs = runtimeEvents.thresholdMs();
        writer.writef("## Safepoints%n%n");
        writer.writeDoc(getClass(), OutputUtils.DOCS_PATH.resolve("safepoint").resolve("safepoint.md"));
        writer.writef("%n%n");
        writer.writeAggregateSection("Total safepoint time", safepoints.aggregate().totalTimeDistribution(), thresholdMs, 2);
        writer.writeAggregateSection("Time inside a safepoint", safepoints.aggregate().insideTimeDistribution(), thresholdMs, 2);
        writer.writeAggregateSection("Cleanup time", safepoints.aggregate().cleanupTimeDistribution(), thresholdMs, 2);
        writer.writeAggregateSection("Time to leave safepoint", safepoints.aggregate().leavingTimeDistribution(), thresholdMs, 2);
        writer.writef("## JVM operations in safepoint%n%n");

        var unknownOperations = new HashSet<String>();
        for (var e : OutputUtils.sortedOperationAggregates(safepoints.aggregatesByType())) {
            var operationName = e.getKey();
            var operationAggregate = e.getValue();

            writer.writef("### Operation '%s'%n%n", operationName);
            var description = OutputUtils.DOCS_PATH.resolve("operation").resolve(operationName + ".md");
            if (OutputUtils.docExists(getClass(), description)) {
                writer.writef("#### Description%n%n");
                writer.writeDoc(getClass(), description);
                writer.writef("%n%n");
            } else {
                if (unknownOperations.add(operationName)) {
                    AnsiConsole.err().printf("GC operation '%s' is unknown%n", operationName);
                }
            }

            writer.writef("Period: %.3f (sec/op)%n%n", operationAggregate.averagePausePeriodSec());
            if (operationAggregate.hasInsideTimeNs()) {
                writer.writef(
                    "Throughput lost due to pauses: %.3f (%%) - %.3f (%%)%n%n",
                    operationAggregate.insideSafepointThroughputLoss(),
                    operationAggregate.totalPauseThroughputLoss()
                );
            } else {
                writer.writef(
                    "Throughput lost due to total pauses: %.3f (%%)%n%n",
                    operationAggregate.totalPauseThroughputLoss()
                );
            }
            writer.writeAggregateSection("Total time", operationAggregate.totalTimeDistribution(), thresholdMs, 4);
            writer.writeAggregateSection("Time inside a safepoint", operationAggregate.insideTimeDistribution(), thresholdMs, 4);
            writer.writeAggregateSection("Time to safepoint", operationAggregate.reachingTimeDistribution(), thresholdMs, 4);
            writer.writeAggregateSection("Cleanup time", operationAggregate.cleanupTimeDistribution(), thresholdMs, 4);
            writer.writeAggregateSection("Time to leave safepoint", operationAggregate.leavingTimeDistribution(), thresholdMs, 4);

            var slowSingleVmOperations = runtimeEvents.slowSingleVmOperations().getOrDefault(operationName, List.of());

            if (slowSingleVmOperations.isEmpty()) {
                continue;
            }

            var topSlowVmOperations = slowSingleVmOperations
                .stream()
                .map(SingleVMOperation::safepointLog)
                .sorted(Comparator.comparingLong(SafepointLogRecord::totalTimeNs).reversed())
                .limit(examples)
                .toList();

            if (!topSlowVmOperations.isEmpty()) {
                writer.writef("#### Slow individual safepoints: threshold = %d ms, top %d%n%n", thresholdMs, examples);
                writer.writef("```");
                for (var safepointLog : topSlowVmOperations) {
                    writer.writef("%n%s%n", safepointLog.origin());
                }
                writer.writef("```%n%n");
            }
        }

        if (aggregate.hasReachingTimeNs()) {
            writer.writef("## Time to safepoint%n%n");
            writer.writeDoc(getClass(), OutputUtils.DOCS_PATH.resolve("safepoint").resolve("time_to_safepoint.md"));
            writer.writef("%n%n");
            writer.writeAggregateSection("Cumulative distribution", aggregate.reachingTimeDistribution(), thresholdMs, 3);
        }

        var slowGcs = runtimeEvents.slowGcs()
            .stream()
            .sorted(Comparator.comparingDouble((GcIteration x) -> x.gcLog().finishTimeSec() - x.gcLog().startTimeSec()).reversed())
            .limit(examples)
            .toList();
        if (!slowGcs.isEmpty()) {
            writer.writef("## GC iterations with long pauses: threshold = %d ms, top %d%n%n", thresholdMs, examples);

            for (var slowGc : slowGcs) {
                writer.writef(
                    "### GC iteration %d (%s)%n%n",
                    slowGc.gcLog().gcNum(),
                    TimeUtils.formatDuration(Math.round((slowGc.gcLog().finishTimeSec() - slowGc.gcLog().startTimeSec()) * 1E9))
                );

                writer.writef("#### Slow safepoints%n%n");
                writer.writef("```");
                for (var safepoint : slowGc.safepointLog()) {
                    writer.writef("%n%s%n", safepoint.origin());
                }
                writer.writef("```%n%n");

                writer.writef("#### Gc logs%n%n");
                writer.writef("```%n");
                for (var gcEvent : slowGc.gcLog().records()) {
                    writer.writef("%s%n", gcEvent.origin());
                }
                writer.writef("```%n%n");
            }
        }
        var slowSimultaneousGcs = runtimeEvents.slowSimultaneousGcs();
        if (!slowSimultaneousGcs.isEmpty()) {
            writer.writef("## Simultaneous GC iterations with long pauses: threshold = %d ms%n%n", thresholdMs);

            for (var slowSimultaneousGc : slowSimultaneousGcs) {
                writer.writef(
                    "### GC iterations %s%n%n",
                    slowSimultaneousGc.gcs().stream()
                        .map(gc -> "%d (%s)".formatted(
                            gc.gcNum(),
                            TimeUtils.formatDuration(Math.round((gc.finishTimeSec() - gc.startTimeSec()) * 1E9))
                        ))
                        .toList()
                );

                writer.writef("#### Slow safepoints%n%n");
                writer.writef("```");
                for (var safepoint : slowSimultaneousGc.safepointLog()) {
                    writer.writef("%n%s%n", safepoint.origin());
                }
                writer.writef("```%n");


                for (var slowGc : slowSimultaneousGc.gcs()) {
                    writer.writef("#### GC %d logs%n%n", slowGc.gcNum());
                    writer.writef("```%n");
                    for (var gcEvent : slowGc.records()) {
                        writer.writef("%s%n", gcEvent.origin());
                    }
                    writer.writef("```%n%n");
                }
            }
        }

        Files.writeString(output, writer.toString());
    }
}
